name: cleaning_duty_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-210.4.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  go_router: ^13.2.0
  fluttertoast: ^8.2.4
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.0
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.0.0
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  rxdart: ^0.26.0
  multi_image_picker_plus: ^0.0.4
  photo_manager: ^3.0.0
  image_picker: ^1.0.7
  jwt_decoder: ^2.0.1
  mime: ^1.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#337EEE"
  image: assets/images/splash.png
  android: true
  ios: true
  fullscreen: true
  android_12: 
    image: assets/images/splash.png
    icon_background_color: "#337EEE"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/